name: Global Badge Auto-Update
on:
  schedule:
    - cron: '0 * * * *' # Every hour
  workflow_dispatch:

concurrency:
  group: badge-sync
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-python@0b93645e9ee71758d331261a019660cb0459a0d8 # v5.3.0
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install requests beautifulsoup4 cloudscraper
      - name: Run Sync
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python update_global_badges.py
      - name: Deploy
        run: |
          git config --global user.name "Global-Badges-Automator"
          git config --global user.email "bot@github.com"
          git pull --rebase origin main
          git add global-badges.json
          git commit -m "Auto-sync and repair [Skip CI]" || exit 0
          git push origin main
